import { z } from "zod";
import { buildYaml } from '../utils/helpers.js'

/**
 * Tool: auth.configure-domain
 *
 * Collects AWS Cognito User Pool Domain configuration from the developer and
 * returns a CloudFormation YAML string (AWS::Cognito::UserPoolDomain).
 *
 * Supports both Cognito-prefixed domains and custom domains (via ACM certificate).
 *
 * Output: cognito-userpool-domain.yaml
 * Next step: run auth.plan to validate and preview all changes before deploying
 */

export function registerUserPoolDomainTool(server) {
  server.tool(
    "auth.configure-domain",
    "Configure an AWS Cognito User Pool Domain and return a CloudFormation YAML",
    {
      Domain: z.string().describe("Domain prefix for the Cognito hosted UI (e.g. 'myapp' → myapp.auth.us-east-1.amazoncognito.com), or full custom domain if using ACM certificate"),
      UserPoolId: z.string().describe("ID of the User Pool to associate this domain with"),
      ManagedLoginVersion: z.number().int().min(1).max(2).optional().describe("Managed login page version: 1 (classic) or 2 (new managed login)"),
      CertificateArn: z.string().optional().describe("ACM certificate ARN in us-east-1 for a custom domain (omit for Cognito-prefixed domain)"),
    },

    async ({ Domain, UserPoolId, ManagedLoginVersion, CertificateArn }) => {
      const props = {};

      props.Domain = Domain;
      props.UserPoolId = UserPoolId;
      if (ManagedLoginVersion !== undefined) props.ManagedLoginVersion = ManagedLoginVersion;
      if (CertificateArn) props.CustomDomainConfig = { CertificateArn };

      const yaml = buildYaml(props);

      const cfTemplate = [
        "AWSTemplateFormatVersion: '2010-09-09'",
        "Description: Cognito User Pool Domain generated by cognito-mcp",
        "",
        "Resources:",
        "  CognitoUserPoolDomain:",
        "    Type: AWS::Cognito::UserPoolDomain",
        "    Properties:",
        yaml
          .split("\n")
          .map((l) => `      ${l}`)
          .join("\n"),
      ].join("\n");

      return {
        content: [
          {
            type: "text",
            text: `Here is your Cognito User Pool Domain CloudFormation configuration:\n\n\`\`\`yaml\n${cfTemplate}\n\`\`\`\n\nSave this as \`cognito-userpool-domain.yaml\` in your project.`,
          },
        ],
      };
    }
  );
}
