import { z } from "zod";
import YAML from "yaml";

/**
 * Navigate an object tree and set a value at a dot-separated path,
 * creating intermediate objects as needed.
 */
function setNestedValue(obj, pathSegments, value) {
  let current = obj;
  for (let i = 0; i < pathSegments.length - 1; i++) {
    const key = pathSegments[i];
    if (current[key] === undefined || typeof current[key] !== "object") {
      current[key] = {};
    }
    current = current[key];
  }
  current[pathSegments[pathSegments.length - 1]] = value;
}

/**
 * Navigate an object tree and delete the key at a dot-separated path.
 */
function deleteNestedValue(obj, pathSegments) {
  let current = obj;
  for (let i = 0; i < pathSegments.length - 1; i++) {
    const key = pathSegments[i];
    if (current[key] === undefined || typeof current[key] !== "object") return;
    current = current[key];
  }
  delete current[pathSegments[pathSegments.length - 1]];
}

/**
 * Tool: auth.modify-config
 *
 * Parses an existing CloudFormation YAML template, applies a list of
 * field-level changes (set or delete), and returns the updated YAML.
 *
 * Uses the `yaml` npm package for parsing and serialization to ensure
 * round-trip fidelity with arbitrary YAML input.
 */
export function registerModifyConfigTool(server) {
  server.tool(
    "auth.modify-config",
    "Modify an existing CloudFormation YAML configuration. Parses the input YAML, applies field-level changes (set or delete at any depth using dot-separated paths), and returns the updated YAML. Use this to iteratively refine configurations generated by other tools.",
    {
      existingYaml: z
        .string()
        .describe("The existing CloudFormation YAML template as a string"),
      changes: z
        .array(
          z.object({
            path: z
              .string()
              .describe(
                "Dot-separated path to the field, e.g. 'Resources.CognitoUserPool.Properties.MfaConfiguration'"
              ),
            value: z
              .any()
              .optional()
              .describe("New value to set at the path. Omit when deleting."),
            action: z
              .enum(["set", "delete"])
              .optional()
              .describe("Action: 'set' (default) to add/update, 'delete' to remove the field"),
          })
        )
        .describe("List of changes to apply to the template"),
    },
    async ({ existingYaml, changes }) => {
      let doc;
      try {
        doc = YAML.parse(existingYaml);
      } catch (err) {
        return {
          content: [
            {
              type: "text",
              text: `Failed to parse the provided YAML:\n\n\`${err.message}\`\n\nPlease ensure the input is valid YAML.`,
            },
          ],
        };
      }

      if (!doc || typeof doc !== "object") {
        return {
          content: [
            {
              type: "text",
              text: "The provided YAML did not parse into a valid object. Please provide a complete CloudFormation template.",
            },
          ],
        };
      }

      const applied = [];

      for (const change of changes) {
        const segments = change.path.split(".");
        const action = change.action ?? "set";

        if (action === "delete") {
          deleteNestedValue(doc, segments);
          applied.push(`Deleted: ${change.path}`);
        } else {
          if (change.value === undefined) {
            applied.push(`Skipped: ${change.path} (no value provided for 'set' action)`);
            continue;
          }
          setNestedValue(doc, segments, change.value);
          applied.push(`Set: ${change.path}`);
        }
      }

      const updatedYaml = YAML.stringify(doc, { indent: 2, lineWidth: 0 });

      return {
        content: [
          {
            type: "text",
            text:
              `Here is your modified CloudFormation configuration:\n\n\`\`\`yaml\n${updatedYaml}\`\`\`\n\n` +
              `**Changes applied:**\n${applied.map((a) => `- ${a}`).join("\n")}`,
          },
        ],
      };
    }
  );
}
